"""add paypay and damaecan payment columns

Revision ID: 8bb5c95bf29c
Revises: 23fc5f97c101
Create Date: 2026-09-19 12:29:28.563678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb5c95bf29c'
down_revision: Union[str, None] = '23fc5f97c101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills existing rows to 0 (rather than NULL) at the
    # DB level; matches the ORM-side default=0 used for new rows going forward.
    op.add_column('daily_entries', sa.Column('paypay_payment', sa.Float(), nullable=True, server_default='0'))
    op.add_column('daily_entries', sa.Column('damaecan_payment', sa.Float(), nullable=True, server_default='0'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_entries', 'damaecan_payment')
    op.drop_column('daily_entries', 'paypay_payment')
    # ### end Alembic commands ###
